{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rancher-app.fullname" . }}
  labels:
    {{- include "rancher-app.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
