{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rancher-app.fullname" . }}
  labels:
    {{- include "rancher-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
